name: Publish

on:
  workflow_dispatch: {}
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  publish-stripe-mock:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        name: pakrym-stripe/stripe-mock
        ref: master
        path: stripe-mock
    - run: |
        rm -f ./stripe-mock/openapi/spec3.json
        rm -f ./stripe-mock/openapi/fixtures3.json
        cp openapi/spec3.json stripe-mock/openapi/spec3.json
        cp openapi/fixtures3.json stripe-mock/openapi/fixtures3.json
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        path: stripe-mock
        token: ${{ secrets.BOT_USER_PAT }}
        push-to-fork: pakrym-stripe-bot/stripe-mock
